print("===================")
print("     Má vizitka")
print("===================")
print("")
print("Jméno:Lucie")
print("Věk: 38")
print("Záliby: deskovky, učení, Python a AI")
print("")
print("=============================")